### ISSUE TITLE
Custom launch arguments

### ISSUE THREAD

**Issue by helloer** [rzaba0/soldat-launcher#2]
As a user, I should be able to set launch arguments for the client/server

**Comment by rzaba0** [comment]
Added this option with https://github.com/rzaba0/soldat-launcher/commit/bb3d349b344d8c91075bb848537f525668938fa8 and https://github.com/rzaba0/soldat-launcher/commit/1daf3d2b3b0c07b449d2cdd3376c52fed66e989c. You can set client's launch arguments in Settings > Game, and local server's arguments in Local > Advanced. Launch arguments will be persisted across multiple sessions - they are saved to launcher.json file.
